name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - uses: jurassiscripts/setup-velociraptor@v1

      - name: Format
        run: cd export && deno fmt --check

      - name: Lint
        run: cd export && deno lint

      - name: Tests
        run: cd export && deno test
